on: 
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, edited]
    paths:
      - '**'

name: render R Markdown files to docs

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  render:
    name: render all R Markdown documents 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install known depedencies  
        run: |
          Rscript -e "install.packages('rmarkdown')"
      - name: render all R Markdown documents 
        run: |
          Rscript -e "rmarkdown::render_site('rmd/')"
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1